// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPaySimplificado.Infrastructure.Persistence;

#nullable disable

namespace PicPaySimplificado.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328041313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PicPaySimplificado.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4571002-0a3e-4174-9d7f-4fee06e74886"),
                            Document = "12345678900",
                            Email = "joao.silva@gmail.com",
                            FullName = "João Silva",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cc969c84-7e02-4410-9375-42f1585aef18"),
                            Document = "12300564544",
                            Email = "francisco.chico@gmail.com",
                            FullName = "Francisco Chicote",
                            Type = 2
                        });
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8f0a7c0-3c7a-4fcb-bc17-1c1a8b5b0c11"),
                            Balance = 100m,
                            UserId = new Guid("b4571002-0a3e-4174-9d7f-4fee06e74886")
                        },
                        new
                        {
                            Id = new Guid("7a8183bc-0834-425d-92ab-b5ddfb381445"),
                            Balance = 10m,
                            UserId = new Guid("cc969c84-7e02-4410-9375-42f1585aef18")
                        });
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("PicPaySimplificado.Domain.Entities.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("PicPaySimplificado.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Entities.User", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
